name: CD
on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE_AND_NPM_REGISTRY }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Add NPM token
        run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"

      - name: Install dependencies
        run: yarn install --froken-lockfile

      - name: Deploy to NPM
        run: yarn semantic-release
